using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class gameManager : MonoBehaviour
{
    public static gameManager instance;
    public GameObject player;
    public playerController playerScript;
    public GameObject activeMenu;
    public GameObject pauseMenu;

    bool isPaused;
    void Awake()
    {
        instance = this;
        player = GameObject.FindGameObjectWithTag("Player");
        playerScript=player.GetComponent<playerController>();
    }

    
    void Update()
    {
        if (Input.GetButtonDown("Cancel") &&activeMenu==null)
        {
            statePaused();      
            activeMenu = pauseMenu;
            activeMenu.SetActive(isPaused);
            
        }
    }

    public void statePaused()
    {
        Time.timeScale = 0;
        Cursor.visible = true;
        Cursor.lockState = CursorLockMode.Confined;
        isPaused = !isPaused;
    }

    public void stateUnpaused()
    {
        Time.timeScale = 1;
        Cursor.visible = false;
        Cursor.lockState = CursorLockMode.Locked;
        isPaused= !isPaused;
        activeMenu.SetActive(false);
        activeMenu = null;
    }
}
